try:
    result = 5 / 0
except Exception as e:
    print("Exception thrown")
    print(e)
